services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www
        ports:
            - 8000:80
        networks:
            - laravel_network
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=db
            - DB_USERNAME=root
            - DB_PASSWORD=root

    db:
        image: mysql:8.0
        container_name: laravel-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
        volumes:
            - ./mysql/data:/var/lib/mysql
        networks:
            - laravel_network
        ports:
            - 3306:3306

    webserver:
        image: nginx:alpine
        container_name: nginx-server
        ports:
            - "8001:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network
        depends_on:
            - app

networks:
    laravel_network: